# Change these first
owner: cloudbip # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Jagoanhosting.com
    url: https://www.jagoanhosting.com
  - name: Beon.co.id
    url: https://beon.co.id
  - name: Byakta.com
    url: https://byakta.com
  - name: CLoudbip.com
    url: https://cloudbip.com
  - name: sitemaya.com
    url: https://sitemaya.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.cloudbip.com
  # baseUrl: /your-repo-name
  logoUrl: https://cloudbip.com/wp-content/uploads/2021/07/Cloudbip-Logo-11-1.png
  name: Cloudbip Uptime
  introTitle: "Cloudbip Uptime Monitoring"
  introMessage: Check latest information from cloudbip.com
  navbar:
    - title: Status
      href: /
    - title: Cloudbip.com
      href: https://cloudbip.com/
